### ISSUE TITLE
qt.qpa.screen: QXcbConnection: Could not connect to display Could not connect to any X display.

### ISSUE THREAD

**Issue by vedranius** [openDsh/dash#102]
# Issue

*Make sure you are running the latest version before reporting an issue.*

## Hardware

| Device             | Connection Method | Screen                       | Mobile Device     | Android Auto Version |
| ------------------ | ----------------- | ---------------------------- | ----------------- | -------------------- |
| Raspberry Pi 4 4GB | USB Cable         | Pi-top Display and Pi-top case | Samsung Galaxy S9 | latest       |

Installation Method: Install.sh 

## Description of problem:
I'm running Pi-Top OS (Raspbian)
When I run the ./dash I get the error:
**_qt.qpa.screen: QXcbConnection: Could not connect to display
Could not connect to any X display._**

## Expected Result:
Run Dash and see it on the touchscreen

**Comment by vedranius** [comment]
Was running it through SSH. Now did it on RPi directly and it's fine. But I get the white screen (dark mode) or MTP device error with two Samsung Galaxy phones (S9 and A8)

**Comment by vedranius** [comment]
This solved it:

"sudo apt install --no-install-recommends xserver-xorg-video-all xserver-xorg-input-all xserver-xorg-core xinit x11-xserver-utils git"

But not sure how to change resolution of AndroidAuto?

**Comment by robert5974** [comment]
To change the dpi of Openauto, use the settings icon (gear in the top right
corner of the first tab).  You will have to do it before connecting the
phone since you won't be able to see it after connecting it.

Robert Crowley

**Comment by icecube45** [comment]
Looks like this was resolved, let us know if you still hit issues.
