### ISSUE TITLE
No way to change resolution/DPI? 

### ISSUE THREAD

**Issue by vedranius** [openDsh/dash#103]
In InteligentAuto in a video there is an option under OpenAuto to change resolution/DPI of AndroidAuto but I don't see it in DASH.
So, is there an another way to change it?
Tnx!

**Comment by robert5974** [comment]
It's there in the top right corner of the Openauto window before connecting phone to the pi.

**Comment by vedranius** [comment]
> It's there in the top right corner of the Openauto window before connecting phone to the pi.

Thanks, it was so small I didn't even notice it.
