### ISSUE TITLE
Navigate UI with the keyboard

### ISSUE THREAD

**Issue by nperrachione** [openDsh/dash#120]
Is it possible?

**Comment by robert5974** [comment]
Yes there is a tab in Settings called "Actions".  There you can bind keyboard keys to actions such as volume, navigation through the UI tabs of Dash, etc...

**Comment by rsjudka** [comment]
however if you're looking to navigate all UI components (for example with the arrow keys) then dash currently isnt that "accessible"

mainly because there's no highlight of active components, but also because some of the components were created by me and arent necessarily fully developed lol

**Comment by nperrachione** [comment]
> however if you're looking to navigate all UI components (for example with the arrow keys) then dash currently isnt that "accessible"
> 
> mainly because there's no highlight of active components, but also because some of the components were created by me and arent necessarily fully developed lol

**Comment by nperrachione** [comment]
ahh okey, thanks for the answer. i was looking for that because i don't have a tactil panel and use a mouse in the car can be uncomfortable, so my idea was to make like a mini keyboard near to the pc screen. i am runing dash on a old pc-tablet, not with a raspberry pi.
