### ISSUE TITLE
PI receiving CAN messages with candump can0, but dash values not changing

### ISSUE THREAD

**Issue by thewormhole5** [openDsh/dash#129]
I can see the CAN messages coming in on the terminal. but the values on the dash do not show anything other than --?

**Comment by rsjudka** [comment]
did you select the appropriate interface/mode in the settings window (cog icon in the top right corner of the vehicle page)
?

**Comment by thewormhole5** [comment]
i had it set to can0 and unloader and server was slid to on. my car has an aftermarket computer, ecu master emu black. the openDSH was showing --. i changed my ECU setting "canbus dashboard" from none to user defined and it started to work. thank you for responding, means a lot. now to figure out how to change the mph/kmh to AFR. 
![ecu pre](https://user-images.githubusercontent.com/112274931/189007356-22200c0f-00d2-4c9c-b330-3700dc765b1c.jpg)
![ecu work](https://user-images.githubusercontent.com/112274931/189007362-6dfb284f-47a0-4c52-a7ce-3c7d360338be.jpg)
![setting](https://user-images.githubusercontent.com/112274931/189007368-d59d3776-a25d-4bbe-aef6-d792b35d6c62.jpg)
![working](https://user-images.githubusercontent.com/112274931/189007371-04dc8be9-429a-4a9c-8886-5a2c1e125e80.jpg)
![candump](https://user-images.githubusercontent.com/112274931/189007376-c4a151c4-3a8a-428e-8e1b-d332de38d66d.jpg)

**Comment by rsjudka** [comment]
not sure on your desire to work in c++ but this would be where you'd want to manipulate the speed gauge
https://github.com/openDsh/dash/blob/develop/src/app/pages/vehicle.cpp#L367

and then adding a command/decoder/conversion to extract the AFR here
https://github.com/openDsh/dash/tree/develop/include/obd
https://github.com/openDsh/dash/blob/develop/src/obd

the goal is eventually to have each gauge be customizable but going to take some rework to get there :)

**Comment by thewormhole5** [comment]
this project is so cool. thank you for making this project and your help.

**Comment by thewormhole5** [comment]
im trying to change the "mph" to "afr". but changing line 367 does not change the on screen.
![image](https://user-images.githubusercontent.com/112274931/189543215-e09934f1-180b-4f0b-a315-8de9e958ce6c.png)

**Comment by rsjudka** [comment]
did you rebuild dash after making that change? going into .../dash/build and then running make?

**Comment by thewormhole5** [comment]
yes. running Makefile brings this up. but it does not change the labels.
![image](https://user-images.githubusercontent.com/112274931/190645673-e13609c2-1b3c-4389-b1b3-83b33853018c.png)

**Comment by thewormhole5** [comment]
I was able to figure out what needed to happen, open the Makefile mentioned the click Build at the top of Geany, then "Make". Thank you
