### ISSUE TITLE
./install.sh fails at [ 83%] while building C++

### ISSUE THREAD

**Issue by Batman313v** [openDsh/dash#136]
# Issue

*Make sure you are running the latest version before reporting an issue.*

## Hardware

| Device             | Connection Method | Screen                       | Mobile Device     | Android Auto Version |
| ------------------ | ----------------- | ---------------------------- | ----------------- | -------------------- |
| Raspberry Pi 3B | None         | 7" Touch Screen | None | v.1.EXAMPLE          |

Installation Method: Install.sh

## Description of problem:

While Running the ./install.sh file it reaches 83% and hangs for around 9 hours before failing with this:
```[ 83%] Built target aasdk_proto
[ 83%] Building CXX object CMakeFiles/aasdk.dir/src/Channel/AV/AVInputServiceChannel.cpp.o
[ 83%] Building CXX object CMakeFiles/aasdk.dir/src/Channel/AV/AudioServiceChannel.cpp.o
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[2]: *** [CMakeFiles/aasdk.dir/build.make:82: CMakeFiles/aasdk.dir/src/Channel/AV/AVInputServiceChannel.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:115: CMakeFiles/aasdk.dir/all] Error 2
make: *** [Makefile:171: all] Error 2
Aasdk Make failed with code 1
```

## Expected Result:

./install.sh finishes without an error and builds correctly

## Problem-relevant steps to reproduce:

1. git clone repo
2. cd dash
3. run ./install.sh
4. wait 9 hours for the raspberry pi to stop hanging and error out 

## Traceback (if applicable):
```bash

```

## Additional info:

Don't know a lot about C++ but will do my best to find a solution. Some relevant info that I didn't see in the docs (could have missed it) that the issue started with was the Raspberry pi version. When I created the issue it gave the Raspi 4 4GB as the default. Is the 3B not recommended hardware? It only has 1Gb ram

**Comment by rsjudka** [comment]
the oldest hw ive ever tested on was a 3b+ with 2gb ram, cant confirm if anyone has ever ran with less than that

the error you have there however usually occurs when you run out of memory... might want to limit the number of things running while you run the install script

are you doing this via a DE (gui) or headless?

**Comment by Batman313v** [comment]
> the oldest hw ive ever tested on was a 3b+ with 2gb ram, cant confirm if anyone has ever ran with less than that
> 
> the error you have there however usually occurs when you run out of memory... might want to limit the number of things running while you run the install script
> 
> are you doing this via a DE (gui) or headless?

I'm running the script over ssh however the gui is most likely running. I used the base RPI OS image rather than lite. If it's a memory issue I can upgrade the PI I'm using. I have a spare 4b 8gb that I was planning to use for the final I just like to test with older hardware incase I mess something up and kill it. I'll swap the PI tonight and make sure that fixes it before I close the issue

**Comment by Batman313v** [comment]
I can confirm that upgrading to a RPI with more RAM solves this issue. I tested on a 2GB RPI and ran into zero problems.
