### ISSUE TITLE
Cannot load 3rd party apps

### ISSUE THREAD

**Issue by maskaz** [openDsh/dash#142]
# Issue

I had compile Dash on Buster 32bit, everything works perfect except 3rd party apps.
Click on Load and Dash crash.
Error message: 
./dash: symbol lookup error: /home/pi/dash/lib/plugins/launcher/libapp.so: undefined symbol: XopenDisplay

Driver: kms

I wanna add path to app manually, to check if this will cause error to, but cannot find example, how it should be look in a /home/pi/.config/openDsh/dash.conf file

## Hardware

| Device             | Connection Method | Screen                       | Mobile Device     | Android Auto Version |
| ------------------ | ----------------- | ---------------------------- | ----------------- | -------------------- |
| Raspberry Pi 3 1GB | USB Cable         | Waveshare 7" Screen |  | v.1.EXAMPLE          |

Installation Method: Install.sh

**Comment by robert5974** [comment]
What is the app?

**Comment by maskaz** [comment]
I cannot load any. For previous test builds, after click on Load window opens and i was able to choose, right now Dash only crash. 
I cannot find any info how to set app manually in a config file.
Btw: im trying to create simple phone control app using PyQt5 and ofono (receive calls, end calls, etc)
Maybe my job is pointless  and there is a working solution?

**Comment by jmccoy555** [comment]
Not running on Buster or maybe it was 32bit by any chance? I know I had some odd behaviour with the app loader. Bullseye 64bit did work.

**Comment by rsjudka** [comment]
yep this sounds related to #111

can you try using 64-bit bullseye and see if that works?

**Comment by maskaz** [comment]
Hi
Yes it looks like totaly related, i now use 64bit Bullseye and can load apps, but not mine, i assume that it a problem with "complicated" PyQt apps.

**Comment by rsjudka** [comment]
yeah I remember someone built a similar pyqt app to yours to use in the app launcher (lost the slack history of it however since they took it all away 🥲)

I know they were able to get it to occasionally run, but it would often fail to embed into dash

haven't used pyqt but it's just a python file yes? is it marked as an executable so it can run on its own?

**Comment by maskaz** [comment]
It can be run on side, but that is a challenge and i'm bloody stubborn ;) I will try to figure it out how to make it work. First idea works... partially.

**Comment by maskaz** [comment]
I rewrited app and now works. 
If someone wanna try it is here: https://github.com/maskaz/CC_for_Dash
Btw i'm able to load my app on 32bit Buster, problem resolved by incident with pulseaudio.
After purge pulseaudio and pulseaudio-utils packages and install them again, some problems fixed (on full desktop lxpanel is loading again) and Dash loads external apps.
