### ISSUE TITLE
Install.sh

### ISSUE THREAD

**Issue by Swissh** [openDsh/dash#15]
./install.sh: line 331: cd: ../dash: No such file or directory
./install.sh: line 820: syntax error: unexpected end of file

**Comment by rsjudka** [comment]
what directory are you running this script from? Also how did you clone dash?

**Comment by Swissh** [comment]
I ran the script in the home directory, I was using the youtube video as a guide. Apologies if I was doing something wrong, I thought it was as easy as running the script. It also failed at another point, but *sudo ./install.sh* made it work

**Comment by rsjudka** [comment]
hmm the video was running the script within the repo's directory, which if you were running the script from the home directory that error you were getting atleast makes sense.

Interesting bit about the sudo, I've never had that issue, it usually just prompts me for sudo when it needs to use it.

Well glad you got it working! I'll try a few things to reproduce the errors you were seeing, and try to update our documentation to help people avoid them.
