### ISSUE TITLE
Clarification of License

### ISSUE THREAD

**Issue by nakato** [openDsh/dash#155]
# Issue

I don't see a license in this repository.

Could you please clarify the intended license for this repository?

**Comment by rsjudka** [comment]
ummm 😅 don't think I've ever considered that

tbh wouldn't know where to start in deciding that..

**Comment by nakato** [comment]
Currently, as there isn't a license, the work defaults to an exclusive copyright, which means nobody but the copyright holder can clone, compile, execute, look at or modify the code in this project.  Looking at the issues in this project, that does not seem to be the intent here.  You can read about the impact of not having a license at https://choosealicense.com/no-permission/

I'm not a license expert, but in the case of this project, I would suggest adopting GPLv3.
If you wanted to do that, this GitHub URL will allow you to kick this off from the web https://github.com/openDsh/dash/community/license/new?template=GPL-3.0 or you can copy the GPLv3 text into a file called "LICENSE" at the root of the repository.

While there are many licenses available, and two other popular ones are MIT and Apache, the reason I'd suggest GPLv3 in this context is because the upstream libraries are GPLv3, and that keeps license compatibility simple.

For example, if the Apache license was used, GPL code cannot be used from the Apache licensed project.  https://www.apache.org/licenses/GPL-compatibility.html

MIT is very permissive, but I think that would require constant monitoring of what libraries are used and how they are used in this project, which could be burdensome.

**Comment by nakato** [comment]
@rsjudka 
I wanted to chase this up.  I've got some nix tooling done up to openauto, and I'd like to get dash into it as well so I can see dash in action and also share this nix work.  I think the nix tooling might be rather useful, as getting openauto running wasn't super straightforward due to its sensitivity to the version of its dependencies.  The nix tooling isn't specific to NixOS, it can be used on Arch, Debian, Fedora, etc.

**Comment by rsjudka** [comment]
just added a license! thank you for help

**Comment by rsjudka** [comment]
yes that would be amazing! i know a few ppl have taken the initial steps to getting a build tool/image/etc but never really got too far

if we can get this added for dash it would make setting up and dev work a breeze 😄 

closing because this issue was specific to the license. Please open another issue or find us on Slack to discuss the nix tooling! or a PR if you get there ;)
