### ISSUE TITLE
Android phone USB connection not working

### ISSUE THREAD

**Issue by BogoniZeno** [openDsh/dash#161]
# Issue

*Make sure you are running the latest version before reporting an issue.*

## Hardware

| Raspberry Pi 3b 1GB | USB Cable | television               |  Xiaomi mi 10t lite | Android Auto 11.5  |
| ------------------ | ----------------- | ---------------------------- | ----------------- | -------------------- |

Installation Method: Install.sh or Image

## Description of problem:

I installed it in a weird way because my rpi 3b couldn't compile it all on his own, (tried at least 10 times without success, openauto and dash compilation made it freeze, I think there is not enough ram to do the job), so i emulated an aarch64 machine with debian bullseye installed and 6GB of ram to compile it all and then moved all the folders on the rpi 3b, i managed to open dash but whenever i connect my phone to the rpi my phone says connected to auto, but dash keeps saying "Connect Device to Start Android Auto",  has the problem something to do with the rpi or the "hacky" way in which i installed it?
If the problem is the installation, how can i install it correctly?

## How I installed it
1. to emulate aarch64 i followed this guide: https://blog.jitendrapatro.me/emulating-aarch64arm64-with-qemu-part-1/
2. compiled all the code in the vm
3. mounted the vm disk on my pc and transfered the files from the vm to the SD card of the rpi
4. started the rpi, executed ./install.sh because it was missing something, the rpi froze again once the script tried to install dash, restarted the pi
5. executed dash because i thought i already compiled it on the vm, in fact it opens but i can't connect my phone

## More info
- i don't have a touchscreen to try it on so i'm using a tv connected with HDMI, it shouldn't be a problem but it's better to make it clear
- the rpiOS installed on my rpi is based on debian bullseye 64 bit so i emulated debian bullseye 64 bit
- when i tried to install in the way it's meant to, either it crashed because OOM killer killed a compilation process or the pi froze with the disk yellow/green light always on. It crashed pretty much almost in the same places, around  23% of openauto compilation/installation and around 3/4% of dash
- I tried to compile it in console mode to have as much ram available possibile but it still wasn't enough

**Comment by BogoniZeno** [comment]
## Update
I recompiled everything on an emulated raspberry pi 4 just to be as close as possible as the device where  i would put the compiled code in the end, dash opened without needing tobrun the script again but the phone was still lot veing recognised, after a bit of trial and error i thought that maybe my rpi wasn't seeing my phone as a phone, so i decided to make sure that it was by installing adb and enabling usb debug on my phone, now it works

## For users trying to install this on rpi 3b 
As of now i don't think its's possible to compile it directly on the rpi due to ram limitations (maybe it's not true and I'm just dumb idk), what i did was:
- create a vm on my pc emulating rpi4 following this guide (it's for debian based distro but it works on other distros too, i did it on fedora, just make sure to find the respective packages for your distro): https://gist.github.com/cGandom/23764ad5517c8ec1d7cd904b923ad863
- compile dash in the vm (it's gonna take a long while, be patient, it took me ~2-4 hours)
- once finished compiling, shutdown the vm and mount the root partition onto the pc (you can do it the same way you mounted the boot partition during the install of the vm, just calculate the offset with the other partition)
- mount the root partition of the real rpi onto the pc
- copy the compiled folders to the rpi partition
- unmount both, start your rpi, start dash and there you go

**Comment by rsjudka** [comment]
sorry alot going on here.. firstly i do all my dev work in a VM but havent gotten AA to actually ever start (cant say ive put to much effort into making it work lol)

so it sounds like a permission thing maybe...
do you have `/etc/udev/rules.d/51-dashusb.rules` installed?
https://github.com/openDsh/dash/blob/develop/install.sh#L595
