### ISSUE TITLE
Error when running ./install.sh

### ISSUE THREAD

**Issue by alealpha07** [openDsh/dash#168]
# Error when running ./install.sh

## Hardware

| Device             | Connection Method | Screen                       | |
| ------------------ | ----------------- | ---------------------------- |
| Raspberry Pi 5 8GB | USB Cable         | Official Raspberry 7" Screen |

## Description of problem:

When I run `./install.sh` (same with `sudo bash ./install.sh`) I get the following:
```bash
### PREVIOUS PART WAS FINE ###
/home/aasdk/src/Transport/SSLWrapper.cpp: In constructor ‘aasdk::transport::SSLWrapper::SSLWrapper()’:
/home/aasdk/src/Transport/SSLWrapper.cpp:36:25: warning: ‘int ERR_load_BIO_strings()’ is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
   36 |     ERR_load_BIO_strings();
      |     ~~~~~~~~~~~~~~~~~~~^
In file included from /usr/include/openssl/cryptoerr.h:17,
                 from /usr/include/openssl/crypto.h:38,
                 from /usr/include/openssl/bn.h:26,
                 from /usr/include/openssl/engine.h:24,
                 from /home/aasdk/src/Transport/SSLWrapper.cpp:20:
/usr/include/openssl/cryptoerr_legacy.h:31:27: note: declared here
   31 | OSSL_DEPRECATEDIN_3_0 int ERR_load_BIO_strings(void);
      |                           ^~~~~~~~~~~~~~~~~~~~
/home/aasdk/src/Transport/SSLWrapper.cpp: In destructor ‘virtual aasdk::transport::SSLWrapper::~SSLWrapper()’:
/home/aasdk/src/Transport/SSLWrapper.cpp:42:5: error: ‘FIPS_mode_set’ was not declared in this scope
   42 |     FIPS_mode_set(0);
      |     ^~~~~~~~~~~~~
make[2]: *** [CMakeFiles/aasdk.dir/build.make:510: CMakeFiles/aasdk.dir/src/Transport/SSLWrapper.cpp.o] Errore 1
make[2]: *** Attesa per i processi non terminati....
make[1]: *** [CMakeFiles/Makefile2:100: CMakeFiles/aasdk.dir/all] Errore 2
make: *** [Makefile:156: all] Errore 2
Aasdk Make failed with code 1
```
(sorry some parts of the traceback are in italian, I love how linux decides to transate even things it shouldn't)

any possible solution?

**Comment by TLMcNulty** [comment]
Your reports on https://github.com/openDsh/dash/pull/165 may be helpful. Can you please fetch `breakingspell:install-overhaul` and rerun? Pi 5 testing has been limited, but it is possible. https://opendsh.slack.com/archives/C01A55C5TD3/p1715326082576639

Slack messages suggest the fixes for FIPS_mode_set are included in that branch.

**Comment by alealpha07** [comment]
Thanks this solved my problem!
