### ISSUE TITLE
aasdk error during installation script at 94%

### ISSUE THREAD

**Issue by Setrias** [openDsh/dash#169]
## Hardware

| Device             | Screen                       |
| ------------------ | ---------------------------- |
| Raspberry Pi 4 4GB | Waveshare 8" Screen |

Installation Method: Install.sh

## Description of problem:

I tried installing it for the third time and it still throws me this error.

## Traceback (if applicable):
```bash

/home/tomas/aasdk/src/Transport/SSLWrapper.cpp: In destructor â€virtual aasdk::transport::SSLWrapper::~SSLWrapper()â€™:
/home/tomas/aasdk/src/Transport/SSLWrapper.cpp:42:5: error: â€FIPS_mode_setâ€™ was not declared in this scope
   42 |     FIPS_mode_set(0);
      |     ^~~~~~~~~~~~~
make[2]: *** [CMakeFiles/aasdk.dir/build.make:510: CMakeFiles/aasdk.dir/src/Transport/SSLWrapper.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:100: CMakeFiles/aasdk.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
Aasdk Make failed with code 1

```
Edit: unknown characters in snippet
![image](https://github.com/openDsh/dash/assets/120753497/24aa4f88-0c00-4496-bad7-fb298fc9120d)

**Comment by TLMcNulty** [comment]
Thanks for the report. Could you please test the branch provided in https://github.com/openDsh/dash/pull/165 and report if it fixes it or not? The presence of some of the characters in your snippet make me wonder but FIPS_mode has been an easy fix with this.

**Comment by Setrias** [comment]
I tried the branch in #165 but it still throws exactly the same err..

**Comment by breakingspell** [comment]
Is locale set properly on the system? It may be something other than Unicode (UTF-8) to return those characters. 

It shouldn't fail on `FIPS_mode_set` though, that's definitely addressed via patch on the fix branch. Since the branch is from a fork, you may have to check it out like this: 

```
git fetch https://github.com/breakingspell/dash.git install-overhaul:install-overhaul
git checkout install-overhaul
./install.sh
```

**Comment by Setrias** [comment]
Oh okay, that fixed it, I must've did something wrong with git, thanks a lot. Also for Android auto to work I had to disable RT Audio. Now it works nicely
