### ISSUE TITLE
pulseaudio git repository error

### ISSUE THREAD

**Issue by bbetter173** [openDsh/dash#177]
# Issue

*Make sure you are running the latest version before reporting an issue.*

## Hardware

| Device             | Connection Method | Screen                       | Mobile Device     | Android Auto Version |
| ------------------ | ----------------- | ---------------------------- | ----------------- | -------------------- |
| Raspberry Pi 4 8GB | USB Cable         | Official Raspberry 7" Screen | Samsung Galaxy S8 | v.1.EXAMPLE          |

Installation Method: `Install.sh`

## Description of problem:

Error when cloning `git://anongit.freedesktop.org/pulseaudio/pulseaudio`:
```
Cloning into 'pulseaudio'...
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I've tested this from multiple PC's and internet connections. The exact error message varies but the result is the same:

```
Cloning into 'pulseaudio'...
fatal: read error: Connection reset by peer
```

## Expected Result:

Pulseaudio builds correctly, or the script exits with an error if this is a necessary step (?)

## Additional info:

Easily fixed by updating the git clone line to:
```
git clone https://gitlab.freedesktop.org/pulseaudio/pulseaudio.git
```

**Comment by TLMcNulty** [comment]
Thanks for putting that fixed line in, I had to fix some users on the fly. I expected the old endpoint to come back at some point but apparently maybe they migrated or something. If you could PR changes for this that would be great, otherwise I'll do it when I can.

**Comment by breakingspell** [comment]
I did notice the old endpoint worked in testing today (`git://`), perhaps this wasn't the only project affected. Should be future-proofed regardless now!

**Comment by robert5974** [comment]
Did you make a Pull Request yet?  If not, go ahead and make the
contribution.  Thanks for finding a resolution.

Robert Crowley

**Comment by robert5974** [comment]
Nevermind lol.  You have of course

Robert Crowley

**Comment by breakingspell** [comment]
Yeah, we're set. Thanks for catching this @bbetter173!
