### ISSUE TITLE
Add Community health files

### ISSUE THREAD

**Issue by matt2005** [openDsh/dash#25]
In order to standardise issue reporting and contributing guidelines I recommend

Adding Community health file into repo root as per link below
[Community Health files](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/creating-a-default-community-health-file)

**Comment by matt2005** [comment]
I've submitted a PR for the Issue and pull request templates.
I wasn't sure what to put in the CODE_OF_CONDUCT.md and CONTRIBUTING.md files.
I can write a standard file and open it up for discussion with the maintainers.

@jcwenger @icecube45 @rsjudka

**Comment by rsjudka** [comment]
ill let others look at the PR first, I want to make sure the issue template has all the "initial" questions we ask anytime someone comes to use with an issue
