### ISSUE TITLE
AA fullscreen

### ISSUE THREAD

**Issue by rsjudka** [openDsh/dash#27]
there should be a setting to force fullscreen AA when it connects

fullscreen AA should also be toggleable with a long press (in addition to the current double tap)

maybe AA could go fullscreen with no touch activity after x seconds? Definitely want to make this optional tho

**Comment by icecube45** [comment]
I'd also like to suggest toggles based on existing buttons.
I.e. if I hold down "play/pause" it would toggle fullscreen AA.

**Comment by rsjudka** [comment]
hmm im a bit confused about that... you mean like the play/pause button in the media page would toggle fullscreen AA?

**Comment by icecube45** [comment]
Ah should have clarified - the shortcut keys (which in my case are steering wheel controls).
i.e. holding down the play/pause key would toggle full screen.

**Comment by rsjudka** [comment]
oh good idea, shortcut should be easy enough to add for that (press and hold not so much tho, ill have to look at the implementation to see how that can be done)

**Comment by icecube45** [comment]
Oh yea having a unique shortcut for it would be nice - I'm just out of steering wheel buttons so my mind jumped first to using an existing shortcut with a modifier (hold down).

**Comment by memtech3** [comment]
Out of steering wheel buttons? ADD MORE! [Universal Steering Wheel Buttons](https://www.amazon.com/Steering-Control-Universal-Wireless-Android/dp/B087PDXDWV/) I bet you could stick at least 4 of these on your steering wheel...

**Comment by rsjudka** [comment]
done in #138
