### ISSUE TITLE
Minimize Dash

### ISSUE THREAD

**Issue by dannybarake** [openDsh/dash#29]
# Issue

Optional minimize dash from control bar to get in rpi desktop environment.

## Hardware

| Device             | Connection Method | Screen                       | Mobile Device     | Android Auto Version |
| ------------------ | ----------------- | ---------------------------- | ----------------- | -------------------- |
| Raspberry Pi 4 8GB | USB Cable         | Official Raspberry 7" Screen | Samsung Galaxy S10+ | latest          |

Installation Method: Install.sh

## Expected Result:

Minimize button in control bar at the bottom when settings is on

**Comment by rsjudka** [comment]
do you think it would be enough to only include the minimize button for a "debug" type of build? Or would it also be beneficial in a release build too?

**Comment by dannybarake** [comment]
@rsjudka i personally prefer it in the release build. I run dash on a raspberry pi besides other applications.
