### ISSUE TITLE
White screen after device connection..![SOLVED]

### ISSUE THREAD

**Issue by Conkali** [openDsh/dash#30]
# Hello all. Nice project ,keep on the good work.

*I updated my OS to latest.*

## Hardware

| Device             | Connection Method | Screen                       | Mobile Device     | Android Auto Version |
| ------------------ | ----------------- | ---------------------------- | ----------------- | -------------------- |
| Raspberry Pi 2 Model b | USB Type C Cable         | OEM 7" Screen | Huawei mate 20 pro ,Samsung A20 | Android 10

Installation Method: Install.sh

## Description of problem:

After i run ./ia androidauto starts , i got the message connect device to start android auto,after i do so android auto starts  On mate 20 pro, i confirm all message but on rpi i got white screen and nothing else. i can navigate in the menu but nothing else. 
![IMG_20201108_202844](https://user-images.githubusercontent.com/73997278/98481177-3ab23000-2201-11eb-88c3-4457e907a5d0.jpg)

**Comment by robert5974** [comment]
Try disabling RTAudio...it has worked for other people

**Comment by Conkali** [comment]
> Try disabling RTAudio...it has worked for other people

It workeddd :) thank you so much. I will change the title to solved for others.
Keep on with the project,we are all here to support.
