### ISSUE TITLE
Changing AA settings - Resolution / Framerate / Scale crashes to desktop

### ISSUE THREAD

**Issue by TheBasedDoge** [openDsh/dash#53]
# Issue

## Hardware

| Device             | Connection Method | Screen                       | Mobile Device     | Android Auto Version |
| ------------------ | ----------------- | ---------------------------- | ----------------- | -------------------- |
| Raspberry Pi 4 4GB | USB C | Official Raspberry 7" Screen | Samsung Galaxy S20+ | latest       |

Installation Method: Install.sh or Image

Fresh Rasbian install with install.sh, on Pi 4 4GB

## Description of problem:

Changing AA settings - Resolution / Framerate / Scale crashes to desktop, re-open and changes are not saved. 

## Expected Result:

DPI and resolution are not able to be changed

## Problem-relevant steps to reproduce:

1. Start Dash with phone disconnected
1. Click the settings wheel at the top right
1.  Adjust any setting, click save and the application crashes to desktop.

## Traceback (if applicable):
```bash

```

## Additional info:

Additional Info

**Comment by rsjudka** [comment]
hi! have you rebooted the pi after going through the install script?

just tried to duplicate your issue but i wasnt seeing any crashes.

could you try running the openauto application (should be found in `~/openauto/bin/autoapp`) and seeing if you can adjust the settings there?

**Comment by TheBasedDoge** [comment]
I did reboot, same issue. I just tried as you suggested and changed it in the openauto application, I click save and it closes, reopen it again and the settings have once again defaulted.

**Comment by TheBasedDoge** [comment]
Oh - I just ran dash as sudo and now its working properly when I hit save.

**Comment by rsjudka** [comment]
hmm... can you check the permissions of the openauto.ini file? Wonder if it was created as the sudo user for whatever reason

**Comment by TheBasedDoge** [comment]
Yeah, i checked it and it was showing as root. I went ahead and deleted all the folders and  reinstalled dash and now it's fine. Onto the rest of the setup now
