### ISSUE TITLE
New widget for parking sensors

### ISSUE THREAD

**Issue by dannybarake** [openDsh/dash#61]
As discussed i would like an widget for parking sensors distance to object for front and rear sensors.
Enabled when putting gear in reverse.

Thanks in advance :-)

**Comment by jakka351** [comment]
my parking sensor module is accessible over the hs-can, maybe could be integrated with socketcan - or overlay on camera page. Have CAN data if anybody needs some for an example.

**Comment by rsjudka** [comment]
widget has been added!
