### ISSUE TITLE
AA not starting via USB, Motorola Phone.

### ISSUE THREAD

**Issue by jakka351** [openDsh/dash#62]
Older Version of Dash works fine for USB and Wireless on my Samsung A30. 

With a brand new Motorola xt2083-3 moto-g play android auto doesnt start when plugged in at the Dash OA page. 

Running Raspbian on RPi4b 4GB, everything works fine on older phones. All usb permissions are set Pi-wise and the phone has AA installed with all permissions enabled. Phone also has AA for car screens app installed with developer mode enabled. 

Have tried with headunit server on and off
Have set in general developer settings USB default mode to file transfer, as initially phone would only be set to charge. 

About to try different usb cable and try manually connecting with wireless AA bypassing dash all together as likely not anything wrong with dash - is this correct spot to post issue?

**Comment by robert5974** [comment]
I read a lot of people have had issues but I see that it may be a security issue.  Someone said they enabled Smart Lock or changed a setting in there then as long as they unlocked their phone via fingerprint then plugged in the usb cable it worked fine even if it were to lock after.

Have you tried that? Maybe even just waking the phone, unlocking, then plug in the usb cable?

**Comment by jakka351** [comment]
Got it to work by removing screen lock, smooth sailing ahead. Thanks
