### ISSUE TITLE
Network streaming camera feed over wifi

### ISSUE THREAD

**Issue by jakka351** [openDsh/dash#65]
Trying to stream my phone screen to the Camera Page, using the screenstream app.

With AA not running, set address to http://x.x.x.x:8080/stream.mjpeg

Camera connects but only displays white screen.

RPi 4 8G.

Opening a browser and connecting to same address in the app launcher page works and can display phone screen stream there. 

Motorola Moto G9 Android 10

**Comment by robert5974** [comment]
It won't work because the camera page is not decoding a stream in the format that a screen would present.  It is decoding formats of cameras such as YUV.  

Those who wrote it could speak more to it but if I'm thinking correctly that would be why.  That's a creative thought though...I could also be wrong lol.

**Comment by stefan-sherwood** [comment]
from https://play.google.com/store/apps/details?id=info.dvkr.screenstream&hl=en_US&gl=US

"WARNING: This app is not designed for streaming video, especially HD video. Use Chromecast instead"

**Comment by stefan-sherwood** [comment]
If you include the Dash debug output from the terminal window, there may be clues as to what is going wrong.

**Comment by jakka351** [comment]
thanks, ill post more info soon. Not trying to stream HD video, messing around with having the Torque pro app gauges display in dash. 

Using either a second phone or an Intel Compute stick running android to stream the gauges, to avoid messing with the AA stream from primary phone.

**Comment by stefan-sherwood** [comment]
Gotcha. It would be excellent to get Torque gauges working.

**Comment by modemlamer** [comment]
try vlc media player as an app in Launcher tab

**Comment by jakka351** [comment]
For anyone interested, I found a tidy solution for displaying TorquePro gauges/decent screen mirroring in Android Auto. https://github.com/shmykelsa/AAAD
