### ISSUE TITLE
Add Audio Equalizer with Presets

### ISSUE THREAD

**Issue by memtech3** [openDsh/dash#78]
Open auto pro has an equalizer with a few presets![MVIMG_20210724_031220.jpg](https://user-images.githubusercontent.com/20732350/126862264-078c5934-140c-4eb9-8bdb-f61f516f7bdd.jpg). Ive found selecting the right preset for your music preference to improve the audio quality quite a bit and would like to see this feature in dash

**Comment by robert5974** [comment]
I've been heavily looking into this.  There are a lot more moving parts than you'd imagine and there are dozens of different implementations.  I am working on a first version of this right now.  Hopefully have something to test in August.

**Comment by robert5974** [comment]
Also there is already an enhancement for this in the issue tracker.  This one can be closed

**Comment by icecube45** [comment]
See #23
