### ISSUE TITLE
install.sh require  pulseaudio-module-bluetooth

### ISSUE THREAD

**Issue by egisz** [openDsh/dash#85]
# Issue

On raspbian Lite, android phone does not pair bluetooth until **pulseaudio-module-bluetooth** installed

## Hardware

| Device             | Connection Method | Screen                       | Mobile Device     | Android Auto Version |
| ------------------ | ----------------- | ---------------------------- | ----------------- | -------------------- |
| Raspberry Pi 4 4GB | Wireless         | video output (composite) | Samsung Galaxy S21 | v.1.EXAMPLE          |

Installation Method: Install.sh

## Description of problem:

On Raspbian Lite, android phone does not pair over bluetooth, error in logs:
```bash
blueman.bluez.errors.DBusFailedError: Protocol not available.
```

Found solution in this [thread](https://askubuntu.com/a/1228816/1193540):

## Expected Result:

Bluetooth pairs out of the box on Raspberry Lite image using command 

## Problem-relevant steps to reproduce:

```
bluetoothctl
discoverable on
pairable on
agent on
default-agent
```

**Comment by robert5974** [comment]
Technically Bluetooth not pairing is an undeveloped feature.  Current implementation only allows a phone to connect and not pair.  I have been looking at building it into dash but currently it's not something that is broken really.  The commands provided are utilizing the Bluez agent which will be the way to go.  It is the handler of authentication of the adapter.
While this is brought up though, does anyone need authentication to require a pin or maybe I should say, does anyone care about a pin to pair via BT?  It can be done with or without.

**Comment by egisz** [comment]
Actually phone pairs, but does not connect without mentioned package...

**Comment by memtech3** [comment]
I just made a PR that adds the pulseaudio module to the install.sh dependencies. Could you test it on your pi and report back?
https://github.com/memtech3/dash/tree/patch-2
#100
