### ISSUE TITLE
Change install script dependency to work on Ubuntu 20.04

### ISSUE THREAD

**Issue by kbader94** [openDsh/dash#86]
# Issue

The dependency "libusb-1.0.0-dev" in install script is incorrectly named for use with Ubuntu 20.04 repositories. Changing the dependency name to "libusb-1.0-0-dev" instead works on both my RPI running Raspberry Pi OS as well as my dev machine running Ubuntu 20.04. I believe this was the only change required to build locally on my development machine. 

## Hardware

| Device             | Connection Method | Screen                       | Mobile Device     | Android Auto Version |
| ------------------ | ----------------- | ---------------------------- | ----------------- | -------------------- |
| AMD Laptop - Ubuntu 20.04 | N/A      | N/A | N/A | N/A          |

Installation Method: Install.sh

## Description of problem:

See Above

## Expected Result:

Install script finds required dependencies

## Problem-relevant steps to reproduce:

1. Launch install script on Ubuntu 20.04

## Traceback (if applicable):

N/A

**Comment by stefan-sherwood** [comment]
The solution I used was to change `install.sh` to use `apt-get` instead of `apt`. `apt-get` resolves the `libusb `naming discrepancy automatically.
