### ISSUE TITLE
In dark mode, not all the icons are changing to white

### ISSUE THREAD

**Issue by egisz** [openDsh/dash#95]
## Description of problem:

As noted [here](https://github.com/openDsh/dash/pull/87#issuecomment-893832515), 
For some reason in dark mode, not all the icons are changing to white. 

![dash-dark-icons](https://user-images.githubusercontent.com/1941760/130188782-4b3ba90d-9a2c-4909-8bbd-5b5644dc18fb.png)

EDIT: Updated screenshot to ephasize problem.

**Comment by stefan-sherwood** [comment]
Can you be more specific about what you're expecting to see?

**Comment by rsjudka** [comment]
this is a legit issue, none of the icons (aside from the ones in the side bar) get colored correctly (basically they are always black which works in light mode but not dark)

I've started working on a fix that doesn't require coloring the icons everytime the theme changes to prevent those crashes

**Comment by stefan-sherwood** [comment]
Ah, ok I see what you're talking about now

**Comment by rsjudka** [comment]
fixed per #106
