### ISSUE TITLE
Segfault when previously connected CAN device is unavailable

### ISSUE THREAD

**Issue by kbader94** [openDsh/dash#97]
I get a segfault on startup if a socketCAN device which was previously connected and selected in the vehicle page is unavailable on startup. If I reconnect the device the segfault goes away.

**Comment by robert5974** [comment]
Can you confirm you are using the latest commit?  We thought this in particular had been fixed a long time ago unless this is something different.

**Comment by icecube45** [comment]
Yea I can't replicate this on the latest commit (tried a few different scenarios), we can reopen this if someone else hits it
